language: php

os:
  - linux

git:
  depth: 1

php:
  - 7.0
sudo: required
dist: precise

install:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpcs ./ --standard=./phpcs.xml

notifications:
  slack: websupporterworkspace:QJO9UDY0e6plhxDtGKwub7en