language: php

os:
  - linux

git:
  depth: 1

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.1
sudo: required
dist: precise
addons:
  apt:
    packages:
      - apache2
  chrome: stable
before_install: phpenv config-rm xdebug.ini

install:
  - mkdir plugin-tmp/
  - cp ./* ./plugin-tmp -r || true
  - mkdir ./public
  - cd plugin-tmp
  - composer install --no-interaction
  - cd ../

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start



  # start selenium
  - wget -c -nc --retry-connrefused --tries=0 http://goo.gl/EoH85x -O selenium-server-standalone.jar
  - echo "Run selenium server - background process"
  - nohup bash -c "java -jar selenium-server-standalone.jar &" && sleep 1; cat nohup.out

  # Create database
  - mysql -e 'CREATE DATABASE wordpress_db;' -uroot
  - mysql -ve "CREATE USER 'wordpress_user'@'localhost' IDENTIFIED BY 'wordpress_db_password'" -uroot
  - mysql -ve "GRANT ALL ON wordpress_db.* TO 'wordpress_user'@'localhost'" -uroot
  - mysql -ve "FLUSH PRIVILEGES" -uroot


  - gunzip tests/behat/data/tickets.sql.gz

  - sed -i "s|full-path-to-repo|$TRAVIS_BUILD_DIR|g" plugin-tmp/behat.yml

  # start apache
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(cat tests/behat/data/.apache-phpenv)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(cat tests/behat/data/.apache-hostfile)" | sed -e "s,PATH,`pwd`/public,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 restart


  # start wp-cli
  - echo "start WP CLI"
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  - wp --info

  # configure WP
  - cd public
  - mkdir tickets
  - cd tickets
  - wp core download
  - ln -s $(pwd)/../../plugin-tmp $(pwd)/wp-content/plugins/support-ticket
  - wp config create --dbname=wordpress_db --dbuser=wordpress_user --dbpass=wordpress_db_password
  - wp db import ../../tests/behat/data/tickets.sql
  - cp $(pwd)/../../tests/behat/data/wp-cli.yml $(pwd)/wp-cli.yml
  - wp rewrite flush --hard
  - cd ../../plugin-tmp/

script:
  - ./vendor/bin/phpcs ./ --standard=./phpcs.xml
  - ./vendor/bin/behat

notifications:
  email: false
  slack: websupporterworkspace:QJO9UDY0e6plhxDtGKwub7en
